let quoteArray = ['In nature, nothing is perfect and everything is perfect. Trees can be contorted, bent in weird ways, and they’re still beautiful. –Alice Walker',
'Forget not that the earth delights to feel your bare feet and the winds long to play with your hair. —Khalil Gibran',
'Look deep into nature, and then you will understand everything better. —Albert Einstein',
'Heaven is under our feet as well as over our heads. —Henry David Thoreau',
'To me a lush carpet of pine needles or spongy grass is more welcome than the most luxurious Persian rug. —Helen Keller',
'We don’t inherit the earth from our ancestors, we borrow it from our children. —Native American proverb',
'I believe in God, only I spell it Nature. —Frank Lloyd Wright',
'Choose only one master—nature. —Rembrandt',
'Nature does not hurry, yet everything is accomplished. —Lao Tzu',
'If you truly love nature, you will find beauty everywhere. —Laura Ingalls Wilder',
'There is something infinitely healing in the repeated refrains of nature—the assurance that dawn comes after night, and spring after winter. —Rachel Carson',
'Leave the road, take the trails. —Pythagoras',
'Live in each season as it passes; breathe the air, drink the drink, taste the fruit, and resign yourself to the influence of the earth. —Henry David Thoreau',
'I go to nature to be soothed and healed, and to have my senses put in order. —John Burroughs',
'It is not so much for its beauty that the forest makes a claim upon men’s hearts, as for that subtle something, that quality of air that emanation from old trees, that so wonderfully changes and renews a weary spirit. —Robert Louis Stevenson',
'For most of history, man has had to fight nature to survive; in this century he is beginning to realize that, in order to survive, he must protect it. —Jacques-Yves Cousteau',
'There’s a whole world out there, right outside your window. You’d be a fool to miss it. —Charlotte Eriksson',
'To forget how to dig the earth and to tend the soil is to forget ourselves. —Mahatma Gandhi',
'Preserve and cherish the pale blue dot, the only home we’ve ever known. —Carl Sagan',
'Study nature, love nature, stay close to nature. It will never fail you. —Frank Lloyd Wright',
'The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do. —Galileo Galilei',
'To make a prairie it takes a clover and one bee, One clover, and a bee, And revery. The revery alone will do, If bees are few. —Emily Dickinson',
'Men argue. Nature acts. —Voltaire',
'All my life through, the new sights of Nature made me rejoice like a child. —Marie Curie',
'Colors are the smiles of nature. —Leigh Hunt',
'Land really is the best art. —Andy Warhol',
'Everything in nature invites us constantly to be what we are. —Gretel Ehrlich',
'The best thing one can do when it’s raining is to let it rain. —Henry Wadsworth Longfellow',
'Many eyes go through the meadow, but few see the flowers in it. —Ralph Waldo Emerson',
'Spring is nature’s way of saying, ‘Let’s party!’ —Robin Williams',
'The earth has music for those who listen. —William Shakespeare',
'There are always flowers for those who want to see them. —Henri Matisse',
'The goal of life is to make your heartbeat match the beat of the universe, to match your nature with Nature. —Joseph Campbell',
'The Amen of nature is always a flower. —Oliver Wendell Holmes, Sr.',
'Nature teaches more than she preaches. There are no sermons in stones. It is easier to get a spark out of a stone than a moral. —John Burroughs',
'Adopt the pace of nature. Her secret is patience. —Ralph Waldo Emerson',
'A weed is no more than a flower in disguise. —James Russell Lowell',
'The earth is what we all have in common. —Wendell Berry',
'Although we say mountains belong to the country, actually, they belong to those that love them. —Dogen',
'The least movement is of importance to all nature. The entire ocean is affected by a pebble. —Blaise Pascal',
'The goal of life is living in agreement with nature. —Zeno',
'Use what talents you possess: the woods would be very silent if no birds sang there except those that sang best. —Henry van Dyke',
'Let the rain kiss you. Let the rain beat upon your head with silver liquid drops. Let the rain sing you a lullaby. —Langston Hughes',
'Nature is loved by what is best in us. —Ralph Waldo Emerson',
'Solitary trees, if they grow at all, grow strong. —Winston Churchill',
'A morning-glory at my window satisfies me more than the metaphysics of books. —Walt Whitman',
'The world is not to be put in order. The world is order. It is for us to put ourselves in unison with this order. —Henry Miller',
'One touch of nature makes the whole world kin. —William Shakespeare',
'By discovering nature, you discover yourself. —Maxime Lagacé',
'Time spent amongst trees is never wasted time. —Katrina Mayer',
'Sunshine is delicious, rain is refreshing, wind braces us up, snow is exhilarating; there is really no such thing as bad weather, only different kinds of good weather. —John Ruskin',
'Never, no, never did nature say one thing and wisdom another. —Edmund Burke',
'If we surrendered to earth’s intelligence we could rise up rooted, like trees. —Rainer Maria Rilke',
'The fairest thing in nature, a flower, still has its roots in earth and manure. —D. H. Lawrence',
'Those who contemplate the beauty of the earth find reserves of strength that will endure as long as life lasts. —Rachel Carson',
'The poetry of the earth is never dead. —John Keats',
'I just wish the world was twice as big and half of it was still unexplored. —David Attenborough',
'In all things of nature there is something of the marvelous. —Aristotle',
'The richness I achieve comes from Nature, the source of my inspiration. —Claude Monet',
'The ocean is a mighty harmonist. —William Wordsworth',
'Nature always wears the colors of the spirit. —Ralph Waldo Emerson',
'Nature is just enough; but men and women must comprehend and accept her suggestions. —Antoinette Brown Blackwell',
'I think nature’s imagination is so much greater than man’s, she’s never going to let us relax. —Richard Feynman',
'Deep in their roots, all flowers keep the light. —Theodore Roethke',
'Plant seeds of happiness, hope, success, and love; it will all come back to you in abundance. This is the law of nature. —Steve Maraboldi',
'Between every two pines there is a doorway to a new world. —John Muir',
'Life sucks a lot less when you add mountain air, a campfire and some peace and quiet. —Brooke Hampton',
'Don’t judge each day by the harvest you reap but by the seeds you plant. —Robert Louis Stevenson',
'Let us permit nature to have her way. She understands her business better than we do. —Michel de Montaigne',
'Nature is not a place to visit. It is home. —Gary Snyder',
'I felt my lungs inflate with the onrush of scenery—air, mountains, trees, people. I thought, ‘This is what it is to be happy.’ —Sylvia Plath',
'To sit in the shade on a fine day and look upon verdure is the most perfect refreshment. —Jane Austen',
'I believe a leaf of grass is no less than the journey-work of the stars. —Walt Whitman',
'Nature’s beauty is a gift that cultivates appreciation and gratitude. —Louie Schwartzberg',
'The earth laughs in flowers. —Ralph Waldo Emerson',
'I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived. —Henry David Thoreau',
'Looking at beauty in the world, is the first step of purifying the mind. —Amit Ray',
'Nature is pleased with simplicity. And nature is no dummy. —Isaac Newton',
'Nature is an infinite sphere of which the center is everywhere and the circumference nowhere. —Blaise Pascal',
'Yosemite Valley, to me, is always a sunrise, a glitter of green and golden wonder in a vast edifice of stone and space. —Ansel Adams',
'Love the world as your own self; then you can truly care for all things. —Lao Tzu',
'Should you shield the canyons from the windstorms you would never see the true beauty of their carvings. —Elisabeth Kübler-Ross',
'We still do not know one thousandth of one percent of what nature has revealed to us. —Albert Einstein',
'It is said that the forest has a certain limit if you look straight ahead, but the sides are boundless. —Riccardo Bozzi',
'If you can’t be in awe of Mother Nature, there’s something wrong with you. —Alex Trebek',
'Like music and art, love of nature is a common language that can transcend political or social boundaries. —Jimmy Carter',
'If one way be better than another, that you may be sure is nature’s way. —Aristotle',
'Going to the mountains is like going home. —John Muir',
'Those who find beauty in all of nature will find themselves at one with the secrets of life itself. —L. Wolfe Gilbert',
'The world is mud-luscious and puddle-wonderful. —E. E. Cummings',
'Some of nature’s most exquisite handiwork is on a miniature scale, as anyone knows who has applied a magnifying glass to a snowflake. —Rachel Carson',
'Just living is not enough. One must have sunshine, freedom, and a little flower. —Hans Christian Andersen',
'The beauty of the natural world lies in the details. —Natalie Angier',
'My father considered a walk among the mountains as the equivalent of churchgoing. —Aldous Huxley',
'Every flower is a soul blossoming in nature. —Gerard De Nerval',
'Man’s heart away from nature becomes hard. —Standing Bear',
'I took a walk in the woods and came out taller than the trees. —Henry David Thoreau',
'If you wish to know the divine, feel the wind on your face and the warm sun on your hand. —Buddha',
'Nature is the art of God. —Dante Alighieri',
'Everything in nature is lyrical in its ideal essence, tragic in its fate, and comic in its existence. —George Santanaya']


export {quoteArray};

